# This workflow will build a .NET project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and run unit tests

on:
  push:
    branches: [ "main", "finished" ]
  pull_request:
    branches: [ "main", "finished" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src/TrainingGuides.Web
        dotnet restore
    - name: Build
      run: |
        cd src/TrainingGuides.Web
        dotnet build --no-restore
    - name: Test
      run: |
        cd src/TrainingGuides.Web.Tests
        dotnet test --verbosity normal
